INSERT INTO activities (name) VALUES
  ('Go hiking'),
  ('Go (real) golfing'),
  ('Attend a high school sporting event'),
  ('Attend a college sporting event'),
  ('Attend a professional sporting event'),
  ('Walk downtown'),
  ('Go dancing'),
  ('Go hiking'),
  ('Go camping'),
  ('Stay in a hotel'),
  ('Go to an amusement park'),
  ('Go to a flea market'),
  ('Serve somewhere together'),
  ('See a movie in theaters'),
  ('Watch a movie at home'),
  ('Go to a drive-in movie'),
  ('Visit a local park'),
  ('Visit a museum'),
  ('Stay at a bed + breakfast'),
  ('Watch the sunset'),
  ('Go putt-putt golfing'),
  ('Go to a driving range'),
  ('Go stargazing'),
  ('Play a video game together'),
  ('Go to a state park'), 
  ('Do a scavenger hunt in a grocery/superstore'),
  ('Watch the sunrise'),
  ('Go swimming'),
  ('Go play with animals at a local shelter'),
  ('Go ice skating'),
  ('Go rock climbing'),
  ('Play H.O.R.S.E. (the basketball game)'),
  ('Go for a long drive'),
  ('Play a board game'),
  ('Play a card game'),
  ('Go fishing'),
  ('Go skydiving'),
  ('Build a fort at home'),
  ('Camp inside'),
  ('Go to the beach'),
  ('Go sledding'),
  ('Go skiing/snowboarding'),
  ('Build a snowman'),
  ('Go to a zoo'),
  ('Go geocaching'),
  ('Go to a concert'),
  ('Go to a local community class (ex. cooking)'),
  ('Go bowling'),
  ('Play lazer tag'),
  ('Go go-karting'),
  ('Go to an arcade'),
  ('Go to a water park'),
  ('Test drive a cool vehicle'),
  ('Do a random home science experiment from YouTube'),
  ('Paint'),
  ('Play a sport'),
  ('Build a lego set'),
  ('Carve pumpkins'),
  ('Visit a botanical garden'),
  ('Do an excape room'),
  ('Rent scooters, segways, or bikes to ride around town'),
  ('Go to an archery range'),
  ('Go axe throwing'),
  ('Go to a shooting range'),
  ('Make pottery'),
  ('Take to the skies (helicopter, local plane, or hot air balloon ride'),
  ('Go to a play'),
  ('Make bucket lists (and check at least one idea off'),
  ('Visit to a bookstore or library'),
  ('Build sandcastles'),
  ('Visit a trampoline park'),
  ('Go fruit-picking'),
  ('Go out for coffee/drinks')
;

INSERT INTO meals (name) VALUES
  ('Mexican (authentic)'),
  ('Tex-Mex'),
  ('Dive bar'),
  ('Any fancy restaurant'),
  ('Breakfast place'),
  ('Drive-in'),
  ('Sandwich shop'),
  ('Italian'),
  ('Progressive dinner (each dinner course somewhere else)'),
  ('Fast food'),
  ('Food truck'),
  ('Diner'),
  ('Seafood'),
  ('BBQ'),
  ('Steakhouse'),
  ('Hibachi grill'),
  ('Food court'),
  ('Sushi'),
  ('Buffet'),
  ('Family-style'),
  ('Picnic'),
  ('Indian'),
  ('Thai'),
  ('Chinese (authentic)'),
  ('Chinese (American)'),
  ('Hotdog stand'),
  ('Concession stand'),
  ('Pizza'),
  ('Vegetarian'),
  ('Vegan'),
  ('Mediterranean'),
  ('Cuban'),
  ('Gas station'),
  ('Random meal from existing supplies at home'),
  ('Homemade Italian'),
  ('Homemade pizza'),
  ('Homemade burgers'),
  ('Homemade BBQ'),
  ('Homemade soup'),
  ('Soup'),
  ('Hotel restaurant'),
  ('French'),
  ('Brazilian steakhouse'),
  ('Salad bar'),
  ('Wings'),
  ('Campfire food'),
  ('Homemade breakfast'),
  ('Bakery'),
  ('Delivery'),
  ('Brunch'),
  ('Homemade subs'),
  ('Homemade sandwiches')
;

INSERT INTO desserts (name) VALUES
  ('Cookies (out)'),
  ('Restaurant (any kind)'),
  ('Bakery'),
  ('Donuts'),
  ('Cakes'),
  ('Bundt Cakes'),
  ('Frozen Yogurt'),
  ('Ice Cream'),
  ('Frozen Custard'),
  ('Soft-serve'),
  ('Homemade cake'),
  ('Pie'),
  ('Homemade brownies'),
  ('Homemade ice cream'),
  ('Tiramisu'),
  ('Cobbler'),
  ('Carrot cake'),
  ('Muffins'),
  ('Molten cake'),
  ('Eclairs'),
  ('Lemon tarts'),
  ('Brownies'),
  ('Candy store'),
  ('Fudge'),
  ('Shaved ice'),
  ('Popsicles'),
  ('Sherbet'),
  ('Apple crisp (or any other fruit)'),
  ('Turkish delight'),
  ('Cheesecake'),
  ('Assorted chocolates'),
  ('Cream puffs'),
  ('Milkshakes'),
  ('Malts'),
  ('Homemade puppy chow'),
  ('Chocolate covered anything'),
  ('Rent a fondue fountain'),
  ('Caramels'),
  ('Big pretzels'),
  ('Popcorn from a movie theater'),
  ('Stove popped popcorn'),
  ('Jello'),
  ('Microwave popcorn'),
  ('Homemade banana bread'),
  ('Homemade zucchini bread'),
  ('Cupcakes (out)'),
  ('Homemade cupcakes'),
  ('Shortcake'),
  ('Angelfood cake'),
  ('Homemade cookies (with decorations)'),
  ('Homemade cookies'),
  ('Tarts'),
  ('Mud pies'),
  ('Dirt pudding'),
  ('Apple Snickers salad'),
  ('Dessert pizza'),
  ('Smores'),
  ('Fruit pizza'),
  ('Monkey bread')
;